version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto-17
    commands:
      - echo "Installing dependencies..."
      - mvn clean install
  build:
    commands:
      - echo "Building the project..."
      - mvn package
artifacts:
  files:
    - target/*.jar
